### PR TITLE
initial commit - pushing working test implementation with tape & cheerio

### PR DESCRIPTION
**Pull request by tgrecojs**
hey! 

i've come across this repo and I think it's awesome stuff man! I'm actually going to use this to host my blog while I wait to get my current CMS situation under control. Anyways, i've added a sample test implementation here - let me know what you think about it! I'm going to add some more use cases but I figured I would create this so you could get a look of what's going on 😄

### CODE REVIEW

**Comment by infiniteluke** [comment]
@tgrecojs Thanks a ton for this work! I updated #2 to include my preferences of test framework (Jest). If you feel like taking on the task of converting this (shouldn't be to hard), I would definitely merge.

Thanks again!

**Comment by tgrecojs** [comment]
@infiniteluke got you man! I will migrate these over 👍

**Comment by infiniteluke** [comment]
Thanks @tgrecojs! Can you please write the tests like so: http://facebook.github.io/jest/docs/en/snapshot-testing.html#snapshot-testing-with-jest.

There should be no need for cheerio when doing snapshot tests.

**Comment by tgrecojs** [comment]
got it @infiniteluke 👍  my mistake 😬

**Review by infiniteluke — APPROVED** [review]
Thanks @tgrecojs for this! 🎉

**Pull request merged**
